### ISSUE TITLE
It request fonts with invalid path.

### ISSUE THREAD

**Issue by p-inks** [ejmg/zerm#34]
It seems to be a problem when uri has path.

e.g., when uri is `example.com/blog`, it *should* get fonts from `example.com/blog/assets/fonts/some-font.woff`.
but it sends request to `example.com/assets/fonts/some-font.woff` and receives `HTTP 404`.

You may want to visit [my page](https://p-inks.github.io/pages/) for details\. (that hasn't any contents)

**Comment by ejmg** [comment]
[these are the lines causing your issue](https://github.com/ejmg/zerm/blob/7630603be028ba0de3f812b543ce3ba535d1d508/templates/macros/head.html#L34-L37).

what do you have configured for `base_url` in [config.toml](https://github.com/ejmg/zerm/blob/7630603be028ba0de3f812b543ce3ba535d1d508/config.toml#L2)? have you tried making it `example.com/blog`?

i don't recall all the default behaviors of zola in terms of URL resolution. `get_url(path=...)` may have to be used to fix it, maybe not.

**Comment by p-inks** [comment]
`base_url` does not appear to affect the font request url.

Yes, I was trying to load fonts with `get_url(path=...)`, and fonts are loaded successfully.
But that's loaded twice 😕 (preload first, and loads again in scss?)

In this [site](https://p-inks.github.io/pages/), we can see `FiraCode-Regular.woff2` requested twice.
![image](https://user-images.githubusercontent.com/29687306/128458107-e4bf68b1-4250-4906-8c77-e64a4d7ff9a2.png)
and these are both `FiraCode-Regular.woff2` request's referer
Referer | `https://p-inks.github.io/pages/`
Referer | `https://p-inks.github.io/pages/style.css?h=e41a1dfad61132bf9c9b951051fd04d0ef6427ab6b64efe0bbf1175cbc3f6f3e`

Maybe this help?

**Comment by ejmg** [comment]
so i see your current `base_url` is `pages/`. does it even work at all if you make it the full base domain combined with the suffix? ie `p-inks.github.io/pages`?

while i can't really say i know why it's double loading your fonts, it might have to do with the fact the [scss refers to them in the same way the `font()` macro does](https://github.com/ejmg/zerm/blob/7630603be028ba0de3f812b543ce3ba535d1d508/sass/_font.scss#L6).

while still a hack, changing the path for the fonts loaded in `_font.scss` might give you an immediate solution to the extra load.

**Comment by ejmg** [comment]
let me know if this works for you. i'm not sure if this is an error in the theme's implementation or not, but knowing of a solution for websites hosted from a path like yours would be beneficial for documentation at minimum!

**Comment by p-inks** [comment]
for delayed, forgive my laziness. I have been busy, but I would have had time to comment about the tries.

> does it even work at all if you make it the full base domain combined with the suffix? ie p-inks.github.io/pages?

It loads things from `https://p-inks.github.io/pages/p-inks.github.io/pages`. ;)

  
> changing the path for the fonts loaded in _font.scss might give you an immediate solution to the extra load.  

When I add prefix(`pages/`), the font loading was broken.
Yes, the path in `_font.scss` was already pointing to the correct url.


I tried somethings, but I couldn't find the way to use `preload`ed fonts in scss.
And now, I'm going to try a few things to fix this problem.

**Comment by p-inks** [comment]
It seems solved. 
I added value `anonymous` to `crossorigin` in preload tag (It was empty).

MDN says,
> Setting the attribute name to an empty value, like crossorigin or crossorigin="", is the same as anonymous.

so I thought it would do the same thing. Still, I don't know why this fixes issue.
But it's working well anyway. :/
<br/>
<br/><br/>


https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/preload#cors-enabled_fetches
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin

**Comment by ejmg** [comment]
> for delayed, forgive my laziness. I have been busy, but I would have had time to comment about the tries.

you are not lazy, haha! i just wanted to make sure you found some solution (or not) so that the issue could at least be known and better documented for later. clearly you proved me right in hoping a solution was found :slightly_smiling_face: 

> It loads things from https://p-inks.github.io/pages/p-inks.github.io/pages. ;)

i'm not surprised at all but i had to make sure, it's a weird "bug" and i really didn't have a solution

> It seems solved.
> so I thought it would do the same thing. Still, I don't know why this fixes issue.

having now looked the above links, i am similarly confused by the solution. poking around at your updated website, my own, and the deployed [test branch version of your PR](https://zerm-git-fork-p-inks-testing-ejmg.vercel.app/), I can't see why exactly it makes a difference. clearly it is CORS related, if only as a weird functional consequence of how fonts are handled.
