### ISSUE TITLE
`zola serve` fails because of `config.extra.show_author = true`

### ISSUE THREAD

**Issue by papojari** [ejmg/zerm#58]
`zola serve` fails because of `show_author = true` even though `config.extra.author = "papojari"`. With `show_author = false` it works.

```
➜ zola serve
Building site...
Checking all internal links with anchors.
> Successfully checked 0 internal link(s) with anchors.
-> Creating 16 pages (0 orphan), 3 sections, and processing 0 images
Error: Failed to render section '/git-repos/papojari.codeberg.page/content/authors/_index.md'
Reason: Failed to render 'section.html': error while rendering macro `posts::section_meta`
Reason: Macro `author` is missing the argument `page`
```

**Comment by ejmg** [comment]
you need to give more info such as how you have your blog setup, etc

**Comment by ejmg** [comment]
if you update your version of zerm to the most recent version of master (#f2d9a11cdec4535208bbe5348f546ad02c1f2bf4) and try rebuilding your zola project, does this error still come up?

**Comment by papojari** [comment]
no it's fixed
